/*
 * Converts the Base-Z-47 artwork (Rust byte arrays, 200x125 RGB) into a C
 * header the kernel can carry.
 *
 * Each picture uses at most 256 distinct colours, so a palette plus one index
 * per pixel stores them in a third of the space with a decoder that is a single
 * array lookup. Run-length coding was measured and came out *larger*: the art
 * is dithered, so runs are short.
 *
 *   node tests/gen_images.js
 */
const fs = require("fs");
const path = require("path");

const RAW = "https://raw.githubusercontent.com/KirinDenis/Base-Z-47-Rust-Game/main/BASE-Z47/src/view/";
const OUT = path.join(__dirname, "..", "wasm", "images.h");
const W = 200;
const COUNT = 5;

(async () => {
  const images = [];
  for (let n = 0; n < COUNT; n++) {
    const text = await (await fetch(RAW + `image${n}.rs`)).text();
    const body = text.slice(text.indexOf("[", text.indexOf("return")));
    const nums = body.match(/\d+/g).map(Number);
    const h = Math.floor(nums.length / (W * 3));

    const palette = [];
    const seen = new Map();
    const idx = [];
    for (let i = 0; i + 2 < W * h * 3; i += 3) {
      const c = (nums[i] << 16) | (nums[i + 1] << 8) | nums[i + 2];
      if (!seen.has(c)) {
        seen.set(c, palette.length);
        palette.push(c);
      }
      idx.push(seen.get(c));
    }
    if (palette.length > 256) {
      console.error(`image${n} has ${palette.length} colours, too many for a byte index`);
      process.exit(1);
    }
    images.push({ n, w: W, h, palette, idx });
    console.log(`image${n}: ${W}x${h}, ${palette.length} colours, ${palette.length * 4 + idx.length} bytes`);
  }

  const wrap = (values, perLine) => {
    const out = [];
    for (let i = 0; i < values.length; i += perLine) {
      out.push("    " + values.slice(i, i + perLine).join(","));
    }
    return out.join(",\n");
  };

  let src = `/*
 * Generated by tests/gen_images.js - do not edit.
 *
 * Artwork from the Base-Z-47 Rust game, palette encoded. The guest asks for a
 * picture by index; the host owns the pixels and does the blit, the same way a
 * real system hands out fonts and bitmaps rather than letting a program poke
 * the framebuffer.
 */
#ifndef JVMOS_WASM_IMAGES_H
#define JVMOS_WASM_IMAGES_H

#define IMAGE_COUNT ${COUNT}

`;

  for (const im of images) {
    src += `static const unsigned int image${im.n}_palette[${im.palette.length}] = {\n`;
    src += wrap(im.palette.map((c) => "0x" + c.toString(16).padStart(6, "0")), 8) + "\n};\n\n";
    src += `static const unsigned char image${im.n}_pixels[${im.idx.length}] = {\n`;
    src += wrap(im.idx, 40) + "\n};\n\n";
  }

  src += `typedef struct {
    const unsigned char *pixels;
    const unsigned int *palette;
    unsigned short width;
    unsigned short height;
} image_asset;

static const image_asset g_images[IMAGE_COUNT] = {
${images.map((im) => `    { image${im.n}_pixels, image${im.n}_palette, ${im.w}, ${im.h} }`).join(",\n")}
};

#endif
`;

  fs.writeFileSync(OUT, src);
  const total = images.reduce((a, im) => a + im.palette.length * 4 + im.idx.length, 0);
  console.log(`\nwrote wasm/images.h: ${total} bytes of image data, ${(src.length / 1024) | 0}KB of source`);
})();
