/*
 * Turns the compiled Rust guest into a C array the kernel can carry, since
 * there is no filesystem to load it from yet.
 *
 *   node tests/gen_guest_header.js
 */
const fs = require("fs");
const path = require("path");

const src = path.join(__dirname, "..", "wasm", "guest", "target",
                      "wasm32-unknown-unknown", "release", "sokoban_guest.wasm");
const out = path.join(__dirname, "..", "wasm", "guest_module.h");

const bin = fs.readFileSync(src);

if (!WebAssembly.validate(bin)) {
  console.error("FAIL: the reference validator rejected the guest module");
  process.exit(1);
}

const rows = [];
for (let i = 0; i < bin.length; i += 12) {
  rows.push("    " + [...bin.slice(i, i + 12)].map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", "));
}

fs.writeFileSync(out,
`/*
 * Generated by tests/gen_guest_header.js from wasm/guest - do not edit.
 *
 * Sokoban, written in Rust, compiled to wasm32-unknown-unknown and embedded in
 * the kernel image. It imports set_color, fill_rect, draw_int, width, height
 * and key from the host, and exports frame().
 *
 * ${bin.length} bytes, one page of linear memory.
 */
#ifndef JVMOS_WASM_GUEST_H
#define JVMOS_WASM_GUEST_H

static const unsigned char wasm_guest_module[] = {
${rows.join(",\n")}
};

#endif
`);
console.log(`wrote wasm/guest_module.h (${bin.length} bytes of module)`);
